# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cmartin/Projects/criper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cmartin/Projects/criper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmartin/Projects/criper/CMakeFiles /home/cmartin/Projects/criper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmartin/Projects/criper/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmartin/Projects/criper/CMakeFiles /home/cmartin/Projects/criper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cmartin/Projects/criper/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named criper-mcp

# Build rule for target.
criper-mcp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 criper-mcp
.PHONY : criper-mcp

# fast build rule for target.
criper-mcp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/build
.PHONY : criper-mcp/fast

src/fs_tools/dispatcher.o: src/fs_tools/dispatcher.cpp.o
.PHONY : src/fs_tools/dispatcher.o

# target to build an object file
src/fs_tools/dispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/dispatcher.cpp.o
.PHONY : src/fs_tools/dispatcher.cpp.o

src/fs_tools/dispatcher.i: src/fs_tools/dispatcher.cpp.i
.PHONY : src/fs_tools/dispatcher.i

# target to preprocess a source file
src/fs_tools/dispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/dispatcher.cpp.i
.PHONY : src/fs_tools/dispatcher.cpp.i

src/fs_tools/dispatcher.s: src/fs_tools/dispatcher.cpp.s
.PHONY : src/fs_tools/dispatcher.s

# target to generate assembly for a file
src/fs_tools/dispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/dispatcher.cpp.s
.PHONY : src/fs_tools/dispatcher.cpp.s

src/fs_tools/fs_chmod.o: src/fs_tools/fs_chmod.cpp.o
.PHONY : src/fs_tools/fs_chmod.o

# target to build an object file
src/fs_tools/fs_chmod.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_chmod.cpp.o
.PHONY : src/fs_tools/fs_chmod.cpp.o

src/fs_tools/fs_chmod.i: src/fs_tools/fs_chmod.cpp.i
.PHONY : src/fs_tools/fs_chmod.i

# target to preprocess a source file
src/fs_tools/fs_chmod.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_chmod.cpp.i
.PHONY : src/fs_tools/fs_chmod.cpp.i

src/fs_tools/fs_chmod.s: src/fs_tools/fs_chmod.cpp.s
.PHONY : src/fs_tools/fs_chmod.s

# target to generate assembly for a file
src/fs_tools/fs_chmod.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_chmod.cpp.s
.PHONY : src/fs_tools/fs_chmod.cpp.s

src/fs_tools/fs_copy.o: src/fs_tools/fs_copy.cpp.o
.PHONY : src/fs_tools/fs_copy.o

# target to build an object file
src/fs_tools/fs_copy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_copy.cpp.o
.PHONY : src/fs_tools/fs_copy.cpp.o

src/fs_tools/fs_copy.i: src/fs_tools/fs_copy.cpp.i
.PHONY : src/fs_tools/fs_copy.i

# target to preprocess a source file
src/fs_tools/fs_copy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_copy.cpp.i
.PHONY : src/fs_tools/fs_copy.cpp.i

src/fs_tools/fs_copy.s: src/fs_tools/fs_copy.cpp.s
.PHONY : src/fs_tools/fs_copy.s

# target to generate assembly for a file
src/fs_tools/fs_copy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_copy.cpp.s
.PHONY : src/fs_tools/fs_copy.cpp.s

src/fs_tools/fs_exec.o: src/fs_tools/fs_exec.cpp.o
.PHONY : src/fs_tools/fs_exec.o

# target to build an object file
src/fs_tools/fs_exec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_exec.cpp.o
.PHONY : src/fs_tools/fs_exec.cpp.o

src/fs_tools/fs_exec.i: src/fs_tools/fs_exec.cpp.i
.PHONY : src/fs_tools/fs_exec.i

# target to preprocess a source file
src/fs_tools/fs_exec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_exec.cpp.i
.PHONY : src/fs_tools/fs_exec.cpp.i

src/fs_tools/fs_exec.s: src/fs_tools/fs_exec.cpp.s
.PHONY : src/fs_tools/fs_exec.s

# target to generate assembly for a file
src/fs_tools/fs_exec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_exec.cpp.s
.PHONY : src/fs_tools/fs_exec.cpp.s

src/fs_tools/fs_find.o: src/fs_tools/fs_find.cpp.o
.PHONY : src/fs_tools/fs_find.o

# target to build an object file
src/fs_tools/fs_find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_find.cpp.o
.PHONY : src/fs_tools/fs_find.cpp.o

src/fs_tools/fs_find.i: src/fs_tools/fs_find.cpp.i
.PHONY : src/fs_tools/fs_find.i

# target to preprocess a source file
src/fs_tools/fs_find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_find.cpp.i
.PHONY : src/fs_tools/fs_find.cpp.i

src/fs_tools/fs_find.s: src/fs_tools/fs_find.cpp.s
.PHONY : src/fs_tools/fs_find.s

# target to generate assembly for a file
src/fs_tools/fs_find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_find.cpp.s
.PHONY : src/fs_tools/fs_find.cpp.s

src/fs_tools/fs_grep.o: src/fs_tools/fs_grep.cpp.o
.PHONY : src/fs_tools/fs_grep.o

# target to build an object file
src/fs_tools/fs_grep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_grep.cpp.o
.PHONY : src/fs_tools/fs_grep.cpp.o

src/fs_tools/fs_grep.i: src/fs_tools/fs_grep.cpp.i
.PHONY : src/fs_tools/fs_grep.i

# target to preprocess a source file
src/fs_tools/fs_grep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_grep.cpp.i
.PHONY : src/fs_tools/fs_grep.cpp.i

src/fs_tools/fs_grep.s: src/fs_tools/fs_grep.cpp.s
.PHONY : src/fs_tools/fs_grep.s

# target to generate assembly for a file
src/fs_tools/fs_grep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_grep.cpp.s
.PHONY : src/fs_tools/fs_grep.cpp.s

src/fs_tools/fs_list.o: src/fs_tools/fs_list.cpp.o
.PHONY : src/fs_tools/fs_list.o

# target to build an object file
src/fs_tools/fs_list.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_list.cpp.o
.PHONY : src/fs_tools/fs_list.cpp.o

src/fs_tools/fs_list.i: src/fs_tools/fs_list.cpp.i
.PHONY : src/fs_tools/fs_list.i

# target to preprocess a source file
src/fs_tools/fs_list.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_list.cpp.i
.PHONY : src/fs_tools/fs_list.cpp.i

src/fs_tools/fs_list.s: src/fs_tools/fs_list.cpp.s
.PHONY : src/fs_tools/fs_list.s

# target to generate assembly for a file
src/fs_tools/fs_list.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_list.cpp.s
.PHONY : src/fs_tools/fs_list.cpp.s

src/fs_tools/fs_mkdir.o: src/fs_tools/fs_mkdir.cpp.o
.PHONY : src/fs_tools/fs_mkdir.o

# target to build an object file
src/fs_tools/fs_mkdir.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_mkdir.cpp.o
.PHONY : src/fs_tools/fs_mkdir.cpp.o

src/fs_tools/fs_mkdir.i: src/fs_tools/fs_mkdir.cpp.i
.PHONY : src/fs_tools/fs_mkdir.i

# target to preprocess a source file
src/fs_tools/fs_mkdir.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_mkdir.cpp.i
.PHONY : src/fs_tools/fs_mkdir.cpp.i

src/fs_tools/fs_mkdir.s: src/fs_tools/fs_mkdir.cpp.s
.PHONY : src/fs_tools/fs_mkdir.s

# target to generate assembly for a file
src/fs_tools/fs_mkdir.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_mkdir.cpp.s
.PHONY : src/fs_tools/fs_mkdir.cpp.s

src/fs_tools/fs_move.o: src/fs_tools/fs_move.cpp.o
.PHONY : src/fs_tools/fs_move.o

# target to build an object file
src/fs_tools/fs_move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_move.cpp.o
.PHONY : src/fs_tools/fs_move.cpp.o

src/fs_tools/fs_move.i: src/fs_tools/fs_move.cpp.i
.PHONY : src/fs_tools/fs_move.i

# target to preprocess a source file
src/fs_tools/fs_move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_move.cpp.i
.PHONY : src/fs_tools/fs_move.cpp.i

src/fs_tools/fs_move.s: src/fs_tools/fs_move.cpp.s
.PHONY : src/fs_tools/fs_move.s

# target to generate assembly for a file
src/fs_tools/fs_move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_move.cpp.s
.PHONY : src/fs_tools/fs_move.cpp.s

src/fs_tools/fs_patch.o: src/fs_tools/fs_patch.cpp.o
.PHONY : src/fs_tools/fs_patch.o

# target to build an object file
src/fs_tools/fs_patch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_patch.cpp.o
.PHONY : src/fs_tools/fs_patch.cpp.o

src/fs_tools/fs_patch.i: src/fs_tools/fs_patch.cpp.i
.PHONY : src/fs_tools/fs_patch.i

# target to preprocess a source file
src/fs_tools/fs_patch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_patch.cpp.i
.PHONY : src/fs_tools/fs_patch.cpp.i

src/fs_tools/fs_patch.s: src/fs_tools/fs_patch.cpp.s
.PHONY : src/fs_tools/fs_patch.s

# target to generate assembly for a file
src/fs_tools/fs_patch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_patch.cpp.s
.PHONY : src/fs_tools/fs_patch.cpp.s

src/fs_tools/fs_read.o: src/fs_tools/fs_read.cpp.o
.PHONY : src/fs_tools/fs_read.o

# target to build an object file
src/fs_tools/fs_read.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_read.cpp.o
.PHONY : src/fs_tools/fs_read.cpp.o

src/fs_tools/fs_read.i: src/fs_tools/fs_read.cpp.i
.PHONY : src/fs_tools/fs_read.i

# target to preprocess a source file
src/fs_tools/fs_read.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_read.cpp.i
.PHONY : src/fs_tools/fs_read.cpp.i

src/fs_tools/fs_read.s: src/fs_tools/fs_read.cpp.s
.PHONY : src/fs_tools/fs_read.s

# target to generate assembly for a file
src/fs_tools/fs_read.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_read.cpp.s
.PHONY : src/fs_tools/fs_read.cpp.s

src/fs_tools/fs_remove.o: src/fs_tools/fs_remove.cpp.o
.PHONY : src/fs_tools/fs_remove.o

# target to build an object file
src/fs_tools/fs_remove.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_remove.cpp.o
.PHONY : src/fs_tools/fs_remove.cpp.o

src/fs_tools/fs_remove.i: src/fs_tools/fs_remove.cpp.i
.PHONY : src/fs_tools/fs_remove.i

# target to preprocess a source file
src/fs_tools/fs_remove.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_remove.cpp.i
.PHONY : src/fs_tools/fs_remove.cpp.i

src/fs_tools/fs_remove.s: src/fs_tools/fs_remove.cpp.s
.PHONY : src/fs_tools/fs_remove.s

# target to generate assembly for a file
src/fs_tools/fs_remove.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_remove.cpp.s
.PHONY : src/fs_tools/fs_remove.cpp.s

src/fs_tools/fs_stat.o: src/fs_tools/fs_stat.cpp.o
.PHONY : src/fs_tools/fs_stat.o

# target to build an object file
src/fs_tools/fs_stat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_stat.cpp.o
.PHONY : src/fs_tools/fs_stat.cpp.o

src/fs_tools/fs_stat.i: src/fs_tools/fs_stat.cpp.i
.PHONY : src/fs_tools/fs_stat.i

# target to preprocess a source file
src/fs_tools/fs_stat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_stat.cpp.i
.PHONY : src/fs_tools/fs_stat.cpp.i

src/fs_tools/fs_stat.s: src/fs_tools/fs_stat.cpp.s
.PHONY : src/fs_tools/fs_stat.s

# target to generate assembly for a file
src/fs_tools/fs_stat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_stat.cpp.s
.PHONY : src/fs_tools/fs_stat.cpp.s

src/fs_tools/fs_tail.o: src/fs_tools/fs_tail.cpp.o
.PHONY : src/fs_tools/fs_tail.o

# target to build an object file
src/fs_tools/fs_tail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_tail.cpp.o
.PHONY : src/fs_tools/fs_tail.cpp.o

src/fs_tools/fs_tail.i: src/fs_tools/fs_tail.cpp.i
.PHONY : src/fs_tools/fs_tail.i

# target to preprocess a source file
src/fs_tools/fs_tail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_tail.cpp.i
.PHONY : src/fs_tools/fs_tail.cpp.i

src/fs_tools/fs_tail.s: src/fs_tools/fs_tail.cpp.s
.PHONY : src/fs_tools/fs_tail.s

# target to generate assembly for a file
src/fs_tools/fs_tail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_tail.cpp.s
.PHONY : src/fs_tools/fs_tail.cpp.s

src/fs_tools/fs_write.o: src/fs_tools/fs_write.cpp.o
.PHONY : src/fs_tools/fs_write.o

# target to build an object file
src/fs_tools/fs_write.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_write.cpp.o
.PHONY : src/fs_tools/fs_write.cpp.o

src/fs_tools/fs_write.i: src/fs_tools/fs_write.cpp.i
.PHONY : src/fs_tools/fs_write.i

# target to preprocess a source file
src/fs_tools/fs_write.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_write.cpp.i
.PHONY : src/fs_tools/fs_write.cpp.i

src/fs_tools/fs_write.s: src/fs_tools/fs_write.cpp.s
.PHONY : src/fs_tools/fs_write.s

# target to generate assembly for a file
src/fs_tools/fs_write.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/fs_write.cpp.s
.PHONY : src/fs_tools/fs_write.cpp.s

src/fs_tools/support.o: src/fs_tools/support.cpp.o
.PHONY : src/fs_tools/support.o

# target to build an object file
src/fs_tools/support.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/support.cpp.o
.PHONY : src/fs_tools/support.cpp.o

src/fs_tools/support.i: src/fs_tools/support.cpp.i
.PHONY : src/fs_tools/support.i

# target to preprocess a source file
src/fs_tools/support.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/support.cpp.i
.PHONY : src/fs_tools/support.cpp.i

src/fs_tools/support.s: src/fs_tools/support.cpp.s
.PHONY : src/fs_tools/support.s

# target to generate assembly for a file
src/fs_tools/support.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/fs_tools/support.cpp.s
.PHONY : src/fs_tools/support.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mcp_server.o: src/mcp_server.cpp.o
.PHONY : src/mcp_server.o

# target to build an object file
src/mcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/mcp_server.cpp.o
.PHONY : src/mcp_server.cpp.o

src/mcp_server.i: src/mcp_server.cpp.i
.PHONY : src/mcp_server.i

# target to preprocess a source file
src/mcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/mcp_server.cpp.i
.PHONY : src/mcp_server.cpp.i

src/mcp_server.s: src/mcp_server.cpp.s
.PHONY : src/mcp_server.s

# target to generate assembly for a file
src/mcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/mcp_server.cpp.s
.PHONY : src/mcp_server.cpp.s

src/sandbox.o: src/sandbox.cpp.o
.PHONY : src/sandbox.o

# target to build an object file
src/sandbox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox.cpp.o
.PHONY : src/sandbox.cpp.o

src/sandbox.i: src/sandbox.cpp.i
.PHONY : src/sandbox.i

# target to preprocess a source file
src/sandbox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox.cpp.i
.PHONY : src/sandbox.cpp.i

src/sandbox.s: src/sandbox.cpp.s
.PHONY : src/sandbox.s

# target to generate assembly for a file
src/sandbox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox.cpp.s
.PHONY : src/sandbox.cpp.s

src/sandbox_setup.o: src/sandbox_setup.cpp.o
.PHONY : src/sandbox_setup.o

# target to build an object file
src/sandbox_setup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox_setup.cpp.o
.PHONY : src/sandbox_setup.cpp.o

src/sandbox_setup.i: src/sandbox_setup.cpp.i
.PHONY : src/sandbox_setup.i

# target to preprocess a source file
src/sandbox_setup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox_setup.cpp.i
.PHONY : src/sandbox_setup.cpp.i

src/sandbox_setup.s: src/sandbox_setup.cpp.s
.PHONY : src/sandbox_setup.s

# target to generate assembly for a file
src/sandbox_setup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/criper-mcp.dir/build.make CMakeFiles/criper-mcp.dir/src/sandbox_setup.cpp.s
.PHONY : src/sandbox_setup.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... criper-mcp"
	@echo "... src/fs_tools/dispatcher.o"
	@echo "... src/fs_tools/dispatcher.i"
	@echo "... src/fs_tools/dispatcher.s"
	@echo "... src/fs_tools/fs_chmod.o"
	@echo "... src/fs_tools/fs_chmod.i"
	@echo "... src/fs_tools/fs_chmod.s"
	@echo "... src/fs_tools/fs_copy.o"
	@echo "... src/fs_tools/fs_copy.i"
	@echo "... src/fs_tools/fs_copy.s"
	@echo "... src/fs_tools/fs_exec.o"
	@echo "... src/fs_tools/fs_exec.i"
	@echo "... src/fs_tools/fs_exec.s"
	@echo "... src/fs_tools/fs_find.o"
	@echo "... src/fs_tools/fs_find.i"
	@echo "... src/fs_tools/fs_find.s"
	@echo "... src/fs_tools/fs_grep.o"
	@echo "... src/fs_tools/fs_grep.i"
	@echo "... src/fs_tools/fs_grep.s"
	@echo "... src/fs_tools/fs_list.o"
	@echo "... src/fs_tools/fs_list.i"
	@echo "... src/fs_tools/fs_list.s"
	@echo "... src/fs_tools/fs_mkdir.o"
	@echo "... src/fs_tools/fs_mkdir.i"
	@echo "... src/fs_tools/fs_mkdir.s"
	@echo "... src/fs_tools/fs_move.o"
	@echo "... src/fs_tools/fs_move.i"
	@echo "... src/fs_tools/fs_move.s"
	@echo "... src/fs_tools/fs_patch.o"
	@echo "... src/fs_tools/fs_patch.i"
	@echo "... src/fs_tools/fs_patch.s"
	@echo "... src/fs_tools/fs_read.o"
	@echo "... src/fs_tools/fs_read.i"
	@echo "... src/fs_tools/fs_read.s"
	@echo "... src/fs_tools/fs_remove.o"
	@echo "... src/fs_tools/fs_remove.i"
	@echo "... src/fs_tools/fs_remove.s"
	@echo "... src/fs_tools/fs_stat.o"
	@echo "... src/fs_tools/fs_stat.i"
	@echo "... src/fs_tools/fs_stat.s"
	@echo "... src/fs_tools/fs_tail.o"
	@echo "... src/fs_tools/fs_tail.i"
	@echo "... src/fs_tools/fs_tail.s"
	@echo "... src/fs_tools/fs_write.o"
	@echo "... src/fs_tools/fs_write.i"
	@echo "... src/fs_tools/fs_write.s"
	@echo "... src/fs_tools/support.o"
	@echo "... src/fs_tools/support.i"
	@echo "... src/fs_tools/support.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mcp_server.o"
	@echo "... src/mcp_server.i"
	@echo "... src/mcp_server.s"
	@echo "... src/sandbox.o"
	@echo "... src/sandbox.i"
	@echo "... src/sandbox.s"
	@echo "... src/sandbox_setup.o"
	@echo "... src/sandbox_setup.i"
	@echo "... src/sandbox_setup.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

